name: test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

jobs:
  linux:
    name: linux + ${{ matrix.compiler }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc, clang]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: make
      run: |
        mkdir -p $HOME/src/github.com/user/clone
        cp -R * $HOME/src/github.com/user/clone
        cd $HOME/src/github.com/user/clone

        CC=${{ matrix.compiler }} make

    - name: make test
      run: |
        cd $HOME/src/github.com/user/clone

        CC=${{ matrix.compiler }} make test

  macos:
    name: macos + ${{ matrix.compiler }}
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc, clang]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: make
      run: |
        mkdir -p $HOME/src/github.com/user/clone
        cp -R * $HOME/src/github.com/user/clone
        cd $HOME/src/github.com/user/clone

        CC=${{ matrix.compiler }} make

    - name: make test
      run: |
        cd $HOME/src/github.com/user/clone

        CC=${{ matrix.compiler }} make test

  openbsd:
    name: openbsd
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build and test on OpenBSD
      uses: vmactions/openbsd-vm@v1
      with:
        usesh: true
        prepare: |
          pkg_add git
        run: |
          mkdir -p $HOME/src/github.com/user/clone
          cp -R * $HOME/src/github.com/user/clone
          cd $HOME/src/github.com/user/clone

          make
          make test
